export const recommendedList = [
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
  ];

export  const recentList = [
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
  ];

export  const popularList = [
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Mango Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Triple Berry Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
    {
      title: "Chocolate Avacado Smoothie",
      ingredients: "",
      category: "",
      ratings: 0,
      noOfRatings: 0,
      carbs: 0,
      score: 0,
      calorie: 0,
      noOfComments: 0,
      image: "",
    },
  ];
