export const elementArray = [
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
  {
    elem1: { type: "Wheat", color: "red", percentage: 10 },
    elem2: { type: "Wheat", color: "red", percentage: 20 },
    elem3: { type: "Wheat", color: "red", percentage: 20 },
    elem4: { type: "Wheat", color: "red", percentage: 50 },
  },
];
