export const INGREDIENTS_FILTER = {
  TYPE: [
    'Frozen Treates',
    'Refreshing',
    'Smoothie',
    'Soups',
    'Tea and Tonic',
    'Wholefood',
  ],
  INGREDIENTS_BY_CATEGORY: [
    {
      categoryName: 'All',
      ingredients: [
        'Bell Pepper',
        'Celery',
        'Cucumber',
        'Tomato',
        'Amaranth Greens',
        'Arugula',
        'Beets Greens',
        'Bok Choy',
        'Broccoli Leaf',
        'Cabbage',
        'Collard Greens',
        'Dandelion Greens',
        'Endive',
        'Kale',
        'Mustard Greens',
        'Spinach',
        'Swish Chard',
        'Turnip Greens',
        'Watercress',
        'Almonds',
        'Avocado',
        'Brazil Nuts',
        'Cashews',
        'Chestnuts',
        'Chia Seeds',
        'Cocoa Bean',
        'Coconut',
        'Coconut Oil',
        'Flax Seed',
        'Hazelnuts',
        'Macadamia',
        'Olive Oil',
        'Peanuts',
        'Pecans',
        'Pine Nuts',
        'Pistachio',
        'Sesame Seeds',
        'Sunflower Seeds',
        'Walnuts',
        'Allspice',
        'Cardamom',
        'Cinnamon',
        'Cloves',
        'Ginger Root',
        'Lemon',
        'Lime',
        'Nutmeg',
        'Vanilla Bean',
        'Artichoke',
        'Asparagus',
        'Broccoli',
        'Brussels Sprouts',
        'Cauliflower',
        'Okra',
        'Sprouts',
        'Apple',
        'Banana',
        'Dates',
        'Figs',
        'Cantaloupe',
        'Grapefruit',
        'Grapes',
        'Mangos',
        'Oranges',
        'Papayas',
        'Peaches',
        'Pears',
        'Pineapples',
        'Plums',
        'Tangerines',
        'Watermelon',
        'Anise',
        'Basil',
        'Borage',
        'Caraway',
        'Catnip',
        'Chamomile',
        'Cilantro',
        'Coriander',
        'Dill Weed',
        'Fennel',
        'Lavender',
        'Lemon Grass',
        'Marjoram',
        'Mint',
        'Oregano',
        'Parsley',
        'Rosemary',
        'Saffron',
        'Sage',
        'Spearmint',
        'Stevia',
        'Tarragon',
        'Thyme',
        'Amaranth Greens',
        'Arugula',
        'Beets Greens',
        'Bok Choy',
        'Broccoli Leaf',
        'Cabbage',
        'Collard Greens',
        'Dandelion Greens',
        'Endive',
        'Kale',
        'Mustard Greens',
        'Spinach',
        'Swish Chard',
        'Turnip Greens',
        'Watercress',
        'Almond Milk',
        'Broth',
        'Coconut Milk',
        'Coconut Water',
        'Heavy Cream',
        'Fruit Juice',
        'Goat Milk',
        'Hemp Milk',
        'Ice',
        'Milk',
        'Soy Milk',
        'Sour Cream',
        'Water',
        'Yogurt',
        'Beets',
        'Carrot',
        'Celeriac',
        'Daikon',
        'Jerusalem Artichokes',
        'Jicama',
        'Kohlrabi',
        'Parsnip',
        'Radish',
        'Rutabaga',
        'Turnip',
        'Chives',
        'Garlic',
        'Green Onions',
        'Horseradish',
        'Leeks',
        'Onions',
        'Peppers',
        'Scallions',
        'Shallots',
        'Turmeric',
        'Water Chestnut',
        'Arrowroot',
        'Eggplant',
        'Pumpkin',
        'Squash',
        'Sweet Potato',
        'Zucchini',
      ],
    },
    {
      categoryName: 'Balancer',
      ingredients: ['Bell Pepper', 'Celery', 'Cucumber', 'Tomato'],
    },
    {
      categoryName: 'Berry',
      ingredients: [
        'Amaranth Greens',
        'Arugula',
        'Beets Greens',
        'Bok Choy',
        'Broccoli Leaf',
        'Cabbage',
        'Collard Greens',
        'Dandelion Greens',
        'Endive',
        'Kale',
        'Mustard Greens',
        'Spinach',
        'Swish Chard',
        'Turnip Greens',
        'Watercress',
      ],
    },
    {
      categoryName: 'Fatty',
      ingredients: [
        'Almonds',
        'Avocado',
        'Brazil Nuts',
        'Cashews',
        'Chestnuts',
        'Chia Seeds',
        'Cocoa Bean',
        'Coconut',
        'Coconut Oil',
        'Flax Seed',
        'Hazelnuts',
        'Macadamia',
        'Olive Oil',
        'Peanuts',
        'Pecans',
        'Pine Nuts',
        'Pistachio',
        'Sesame Seeds',
        'Sunflower Seeds',
        'Walnuts',
      ],
    },
    {
      categoryName: 'Flavors',
      ingredients: [
        'Allspice',
        'Cardamom',
        'Cinnamon',
        'Cloves',
        'Ginger Root',
        'Lemon',
        'Lime',
        'Nutmeg',
        'Vanilla Bean',
      ],
    },
    {
      categoryName: 'Flowering',
      ingredients: [
        'Artichoke',
        'Asparagus',
        'Broccoli',
        'Brussels Sprouts',
        'Cauliflower',
        'Okra',
        'Sprouts',
      ],
    },
    {
      categoryName: 'Fruity',
      ingredients: [
        'Apple',
        'Banana',
        'Dates',
        'Figs',
        'Cantaloupe',
        'Grapefruit',
        'Grapes',
        'Mangos',
        'Oranges',
        'Papayas',
        'Peaches',
        'Pears',
        'Pineapples',
        'Plums',
        'Tangerines',
        'Watermelon',
      ],
    },
    {
      categoryName: 'Herbal',
      ingredients: [
        'Anise',
        'Basil',
        'Borage',
        'Caraway',
        'Catnip',
        'Chamomile',
        'Cilantro',
        'Coriander',
        'Dill Weed',
        'Fennel',
        'Lavender',
        'Lemon Grass',
        'Marjoram',
        'Mint',
        'Oregano',
        'Parsley',
        'Rosemary',
        'Saffron',
        'Sage',
        'Spearmint',
        'Stevia',
        'Tarragon',
        'Thyme',
      ],
    },
    {
      categoryName: 'Leafy',
      ingredients: [
        'Amaranth Greens',
        'Arugula',
        'Beets Greens',
        'Bok Choy',
        'Broccoli Leaf',
        'Cabbage',
        'Collard Greens',
        'Dandelion Greens',
        'Endive',
        'Kale',
        'Mustard Greens',
        'Spinach',
        'Swish Chard',
        'Turnip Greens',
        'Watercress',
      ],
    },
    {
      categoryName: 'Liquid',
      ingredients: [
        'Almond Milk',
        'Broth',
        'Coconut Milk',
        'Coconut Water',
        'Heavy Cream',
        'Fruit Juice',
        'Goat Milk',
        'Hemp Milk',
        'Ice',
        'Milk',
        'Soy Milk',
        'Sour Cream',
        'Water',
        'Yogurt',
      ],
    },
    {
      categoryName: 'Rooty',
      ingredients: [
        'Beets',
        'Carrot',
        'Celeriac',
        'Daikon',
        'Jerusalem Artichokes',
        'Jicama',
        'Kohlrabi',
        'Parsnip',
        'Radish',
        'Rutabaga',
        'Turnip',
      ],
    },
    {
      categoryName: 'Seasoning',
      ingredients: [
        'Chives',
        'Garlic',
        'Green Onions',
        'Horseradish',
        'Leeks',
        'Onions',
        'Peppers',
        'Scallions',
        'Shallots',
        'Turmeric',
        'Water Chestnut',
      ],
    },
    {
      categoryName: 'Tube-Squash',
      ingredients: [
        'Arrowroot',
        'Eggplant',
        'Pumpkin',
        'Squash',
        'Sweet Potato',
        'Zucchini',
      ],
    },
  ],
  ALLERGIES: ['Sesame', 'Soy', 'Tree Nut', 'Wheat', 'Corn'],
  DIET: [
    'Keto',
    'Vegan',
    'Vegetarian',
    'Paleo',
    'Whole 30',
    'Low-carb',
    'Diabetic Diet',
    'Gluten Free Diet',
  ],
  EQUIPMENT: ['Blender', 'Strainer', 'Juicer', 'Ice Cream Maker'],
  DRUGS: [
    'Atorvastatin',
    'Levothyroxine',
    'Lisinopril',
    'Metformin',
    'Metoprolol',
    'Amlodipine',
    'Albuterol',
    'Omeprazole',
    'Losartan',
    'Gabapentin',
    'Hydrochlorothiazide',
    'Sertraline',
    'Simvastatin',
    'Montelukast',
    'Acetaminophen; Hydrocodone',
    'Pantoprazole',
    'Furosemide',
    'Fluticasone',
    'Escitalopram',
    'Fluoxetine',
    'Rosuvastatin',
    'Bupropion',
    'Amoxicillin',
    'Dextroamphetamine',
    'Trazodone',
    'Duloxetine',
    'Prednisone',
    'Tamsulosin',
    'Ibuprofen',
    'Citalopram',
    'Meloxicam',
    'Pravastatin',
    'Carvedilol',
    'Potassium',
    'Tramadol',
    'Clopidogrel',
    'Insulin Glargine',
    'Aspirin',
    'Atenolol',
    'Venlafaxine',
    'Alprazolam',
    'Ethinyl Estradiol; Norethindrone',
    'Allopurinol',
    'Hydrochlorothiazide; Lisinopril',
    'Cyclobenzaprine',
    'Clonazepam',
    'Zolpidem',
    'Azithromycin',
    'Oxycodone',
    'Warfarin',
    'Methylphenidate',
    'Apixaban',
    'Ranitidine',
    'Glipizide',
    'Ergocalciferol',
    'Quetiapine',
    'Budesonide; Formoterol',
    'Estradiol',
    'Acetaminophen; Oxycodone',
    'Ondansetron',
    'Naproxen',
    'Glimepiride',
    'Spironolactone',
    'Clonidine',
    'Insulin Lispro',
    'Loratadine',
    'Cetirizine',
    'Topiramate',
    'Lorazepam',
    'Ethinyl Estradiol; Norgestimate',
    'Lamotrigine',
    'Diltiazem',
    'Hydrochlorothiazide; Losartan',
    'Diclofenac',
    'Hydroxyzine',
    'Buspirone',
    'Latanoprost',
    'Paroxetine',
    'Lisdexamfetamine',
    'Fluticasone; Salmeterol',
    'Pregabalin',
    'Propranolol',
    'Cephalexin',
    'Cholecalciferol',
    'Insulin Aspart',
    'Finasteride',
    'Fenofibrate',
    'Sitagliptin',
    'Folic Acid',
    'Doxycycline',
    'Rivaroxaban',
    'Tizanidine',
    'Amoxicillin; Clavulanate',
    'Amitriptyline',
    'Lovastatin',
    'Alendronate',
    'Levetiracetam',
    'Sumatriptan',
    'Hydralazine',
    'Sulfamethoxazole; Trimethoprim',
    'Aripiprazole',
    'Celecoxib',
    'Ferrous Sulfate',
    'Famotidine',
    'Benzonatate',
    'Mirtazapine',
    'Triamcinolone',
    'Ezetimibe',
    'Fluticasone; Vilanterol',
    'Valacyclovir',
    'Methotrexate',
    'Oxybutynin',
    'Ciprofloxacin',
    'Valproate',
    'Triamterene; Hydrochlorothiazide',
    'Thyroid',
    'Diazepam',
    'Nifedipine',
    'Clindamycin',
    'Donepezil',
    'Insulin Detemir',
    'Hydroxychloroquine',
    'Isosorbide',
    'Ethinyl Estradiol; Levonorgestrel',
    'Baclofen',
    'Testosterone',
    'Esomeprazole',
    'Desogestrel; Ethinyl Estradiol',
    'Oseltamivir',
    'Benazepril',
    'Dexmethylphenidate',
    'Tiotropium',
    'Fluconazole',
    'Dulaglutide',
    'Chlorthalidone',
    'Methocarbamol',
    'Enalapril',
    'Metronidazole',
    'Prednisolone',
    'Guanfacine',
    'Verapamil',
    'Liraglutide',
    'Norethindrone',
    'Ropinirole',
    'Acetaminophen',
    'Empagliflozin',
    'Hydrocortisone',
    'Drospirenone; Ethinyl Estradiol',
    'Risperidone',
    'Meclizine',
    'Albuterol; Ipratropium',
    'Adalimumab',
    'Nortriptyline',
    'Valsartan',
    'Cyanocobalamin',
    'Etonogestrel; Ethinyl Estradiol',
    'Acyclovir',
    'Phentermine',
    'Cefdinir',
    'Timolol',
    'Methylprednisolone',
    'Oxcarbazepine',
    'Morphine',
    'Olmesartan',
    'Dicyclomine',
    'Pramipexole',
    'Azelastine',
    'Insulin Degludec',
    'Memantine',
    'Prazosin',
    'Ketoconazole',
    'Rizatriptan',
    'Acetaminophen; Codeine',
    'Promethazine',
    'Metformin; Sitagliptin',
    'Anastrozole',
    'Desvenlafaxine',
    'Ramipril',
    'Pioglitazone',
    'Clobetasol',
    'Irbesartan',
    'Levofloxacin',
    'Amiodarone',
    'Nitroglycerin',
    'Olanzapine',
    'Sucralfate',
    'Docusate',
    'Progesterone',
    'Mirabegron',
    'Mupirocin',
    'Nebivolol',
    'Nitrofurantoin',
    'Levocetirizine',
    'Methimazole',
    'Cyclosporine',
    'Sildenafil',
    'Carbamazepine',
    'Labetalol',
    'Calcium; Cholecalciferol',
    'Lansoprazole',
  ],
};
export const recipeSliderImage = [
  '/images/recipe_banner_dummy/recipe-slider-img1.png',
  '/images/recipe_banner_dummy/recipe-slider-img2.png',
  '/images/recipe_banner_dummy/recipe-slider-img3.png',
  '/images/recipe_banner_dummy/recipe-slider-img4.png',
];

export const ingredients = [
  {
    id: '1ingredientLeafy',
    title: 'Kale',
    img: '/images/food/chard.png',
    servings: 1,
    measuring_scale: 'whole',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '2ingredientLeafy',
    title: 'Collard',
    img: '/images/food/Dandelion.png',
    servings: 2,
    measuring_scale: 'cups',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '3ingredientLeafy',
    title: 'Swiss Chard',
    img: '/images/food/chard.png',
    servings: 2,
    measuring_scale: 'cups',
    extra_sentence: ',cut up',
    checked: false,
  },
];

export const recipeComments = [
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
  {
    name: 'Iris Loo',
    comment:
      'I love this recipe because I enjoy clean simple flavours. I paired it with spicy crumbly tempeh.',
    data: '27/5/2021',
  },
];

export let ingredientLeafy = [
  {
    id: '1ingredientLeafy',
    title: 'Kale',
    img: '/images/food/chard.png',
    servings: 1,
    measuring_scale: 'whole',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '2ingredientLeafy',
    title: 'Collard',
    img: '/images/food/Dandelion.png',
    servings: 2,
    measuring_scale: 'cups',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '3ingredientLeafy',
    title: 'Swiss Chard',
    img: '/images/food/chard.png',
    servings: 2,
    measuring_scale: 'cups',
    extra_sentence: ',cut up',
    checked: false,
  },
  {
    id: '4ingredientLeafy',
    title: 'Peas',
    img: '/images/food/spinach.png',
    servings: 1,
    measuring_scale: 'medium',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '5ingredientLeafy',
    title: 'Onion',
    img: '/images/food/collard_greens.png',
    servings: 1,
    measuring_scale: 'whole',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '6ingredientLeafy',
    title: 'Cauliflower',
    img: '/images/food/fresh.png',
    servings: 1,
    measuring_scale: 'cups',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '7ingredientLeafy',
    title: 'Kale1',
    img: '/images/food/chard.png',
    servings: 1,
    measuring_scale: 'whole',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '8ingredientLeafy',
    title: 'Collard1',
    img: '/images/food/Dandelion.png',
    servings: 1,
    measuring_scale: 'medium',
    extra_sentence: '',
    checked: false,
  },
  {
    id: '9ingredientLeafy',
    title: 'Swiss Chard1',
    img: '/images/food/chard.png',
    servings: 2,
    measuring_scale: 'cups',
    extra_sentence: ',cut up',
    checked: false,
  },
];

export const filterRankingList = [
  { name: 'Mustard Greens', percent: 103 },
  { name: 'Swish Chards', percent: 95 },
  { name: 'Arugula', percent: 90 },
  { name: 'Beet Greens', percent: 80 },
  { name: 'Kale', percent: 75 },
];
