export let ingredientLeafy = [
  {
    id: "1ingredientLeafy",
    title: "Kale",
    img: "/food/chard.png",
    servings: 1,
    measuring_scale: "whole",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "2ingredientLeafy",
    title: "Collard",
    img: "/food/dandelion.png",
    servings: 2,
    measuring_scale: "cups",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "3ingredientLeafy",
    title: "Swiss Chard",
    img: "/food/chard.png",
    servings: 2,
    measuring_scale: "cups",
    extra_sentence: ",cut up",
    checked: false,
  },
  {
    id: "4ingredientLeafy",
    title: "Peas",
    img: "/food/spinach.png",
    servings: 1,
    measuring_scale: "medium",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "5ingredientLeafy",
    title: "Onion",
    img: "/food/collard_greens.png",
    servings: 1,
    measuring_scale: "whole",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "6ingredientLeafy",
    title: "Cauliflower",
    img: "/food/fresh.png",
    servings: 1,
    measuring_scale: "cups",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "7ingredientLeafy",
    title: "Kale1",
    img: "/food/chard.png",
    servings: 1,
    measuring_scale: "whole",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "8ingredientLeafy",
    title: "Collard1",
    img: "/food/dandelion.png",
    servings: 1,
    measuring_scale: "medium",
    extra_sentence: "",
    checked: false,
  },
  {
    id: "9ingredientLeafy",
    title: "Swiss Chard1",
    img: "/food/chard.png",
    servings: 2,
    measuring_scale: "cups",
    extra_sentence: ",cut up",
    checked: false,
  },
];

export const filterRankingList = [
  { name: "Mustard Greens", percent: 103 },
  { name: "Swish Chards", percent: 95 },
  { name: "Arugula", percent: 90 },
  { name: "Beet Greens", percent: 80 },
  { name: "Kale", percent: 75 },
];
