export const recommendedList = [
  {
    title: "Chocolate Avacado Mango Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Triple Berry Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Mango Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Triple Berry Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Mango Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Triple Berry Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Mango Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Triple Berry Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
  {
    title: "Chocolate Avacado Smoothie",
    ingredients: "",
    category: "",
    ratings: 0,
    noOfRatings: 0,
    carbs: 0,
    score: 0,
    calorie: 0,
    noOfComments: 0,
    image: "",
  },
];

export const nutrition = [
  {
    section: "Energy",
    amount: [
      {
        label: "Total Carbohydrates",
        value: "39.2 g",
        daily: 12,
      },
      {
        label: "Dietary Fiber",
        value: "15.9 g",
        daily: 60,
      },
      {
        label: "Sugars Protein",
        value: "6.4 g",
        daily: 8,
      },
      {
        label: "potein",
        value: "17.2 g",
        daily: 34,
      },
    ],
  },
  {
    section: "Vitamins",
    amount: [
      {
        label: "Vitamin A",
        value: "30.202 iu",
        daily: 12,
      },
      {
        label: "Vitamin B",
        value: "480 mg",
        daily: 356,
      },
      {
        label: "Vitamin K",
        value: "1800 ug",
        daily: 123,
      },
      {
        label: "Folate",
        value: "200 ug",
        daily: 90,
      },
    ],
  },
  {
    section: "Minerals",
    amount: [
      {
        label: "Potassium",
        value: "296 mg",
        daily: 32,
      },
      {
        label: "Iron",
        value: "9 mg",
        daily: 39,
      },
      {
        label: "Calcium",
        value: "600 mg",
        daily: 232,
      },
    ],
  },
  {
    section: "Phythonutrients",
    amount: [
      {
        label: "Vitexin",
        value: "296 mg",
        daily: 32,
      },
      {
        label: "Betaxanthins",
        value: "9 mg",
        daily: 39,
      },
      {
        label: "Kaempferol",
        value: "600 mg",
        daily: 232,
      },
      {
        label: "Betaxanthins",
        value: "296 mg",
        daily: 39,
      },
      {
        label: "Betaxanthins",
        value: "9 mg",
        daily: 39,
      },
      {
        label: "Kaempferol",
        value: "600 mg",
        daily: 232,
      },
    ],
  },
];
