import { WikiListType } from "../../../type/wikiListType";

const dummyData: { [key: string]: WikiListType[] } = {
  Nutrient: [
    {
      _id: "620b4606b82695d67f28e193",
      wikiTitle: "Calorie",
      wikiDescription: "This is short description .",
      type: "Nutrient",
      category: "Calories",
      image: "",
      status: "Active",
      portions: null,
      publishedBy: "g. braun",
      description: "",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b4607b82695d67f28e196",
      wikiTitle: "Protien with title",
      wikiDescription: "This is short description for protien nutrient",
      type: "Nutrient",
      category: "Energy",
      image: "",
      status: "Active",
      portions: null,
      publishedBy: "g. braun",
      description: "",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b4607b82695d67f28e199",
      wikiTitle: "Fats ",
      wikiDescription: "This is a little description  at Nutrient ...",
      type: "Nutrient",
      category: "Energy",
      image: "",
      status: "Active",
      portions: null,
      publishedBy: "g. braun",
      description: "",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b4608b82695d67f28e19c",
      wikiTitle: "Carbohydrates",
      wikiDescription: "Carbohydrates with short description... ",
      type: "Nutrient",
      category: "Energy",
      image: "",
      status: "Active",
      portions: null,
      publishedBy: "g. braun",
      description: "",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
  ],

  Ingredient: [
    {
      _id: "620b6bce40d3f19b558f0bc1",
      wikiTitle: "Amaranth greens",
      wikiDescription: " ",
      type: "Ingredient",
      category: "Leafy",
      image: "https://blending.s3.us-east-1.amazonaws.com/7826404.png",
      status: "Active",
      portions: [
        {
          measurement: "cup",
          meausermentWeight: "28",
          default: true,
        },
        {
          measurement: "leaf",
          meausermentWeight: "14",
          default: false,
        },
        {
          measurement: "mug",
          meausermentWeight: "100",
          default: false,
        },
      ],
      publishedBy: "g. braun",
      description: "Amaranth leaves, raw",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b6bd640d3f19b558f0c1e",
      wikiTitle: "Apple juice",
      wikiDescription:
        "This is organic apple juice vary healthy for body and refreshing for mind . ",
      type: "Ingredient",
      category: "Liquid",
      image: "https://blending.s3.us-east-1.amazonaws.com/6617479.jpeg",
      status: "Active",
      portions: [
        {
          measurement: "cup",
          meausermentWeight: "100",
          default: true,
        },
      ],
      publishedBy: "g. braun",
      description:
        "Apple juice, with added vitamin C, from concentrate, shelf stable",
      isPublished: true,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b6bfd40d3f19b558f0d1f",
      wikiTitle: "Gala apple",
      wikiDescription: " ",
      type: "Ingredient",
      category: "Fruity",
      image: null,
      status: "Active",
      portions: [
        {
          measurement: "cup",
          meausermentWeight: "100",
          default: true,
        },
      ],
      publishedBy: "g. braun",
      description: "Apples, gala, with skin, raw",
      isPublished: null,
      commentsCount: null,
      hasInCompare: null,
    },
    {
      _id: "620b6c0640d3f19b558f0d5a",
      wikiTitle: "Granny smith apple",
      wikiDescription: " ",
      type: "Ingredient",
      category: "Fruity",
      image: null,
      status: "Active",
      portions: [
        {
          measurement: "cup",
          meausermentWeight: "100",
          default: true,
        },
      ],
      publishedBy: "g. braun",
      description: "Apples, granny smith, with skin, raw",
      isPublished: null,
      commentsCount: null,
      hasInCompare: null,
    },
  ],

  Health: [],
};

export default dummyData;
