name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing the dependencies
        run:
          yarn

          # creating .env.production
      - name: Creating .env.production
        run: echo 'NEXT_PUBLIC_AWS_REGION= ${{ secrets.AWS_REGION }}' >> .env.production && echo 'NEXT_PUBLIC_AWS_COGNITO_REGION= ${{ secrets.AWS_REGION }}' >> .env.production && echo 'NEXT_PUBLIC_AWS_COGNITO_POOL_ID= ${{ secrets.AWS_COGNITO_POOL_ID }}' >> .env.production && echo 'NEXT_PUBLIC_AWS_APP_CLIENT_ID= ${{ secrets.AWS_APP_CLIENT_ID }}' >> .env.production && echo 'NEXT_PUBLIC_OAUTH_DOMAIN= ${{ secrets.AWS_COGNITO_OAUTH_DOMAIN }}' >> .env.production && echo 'NEXT_PUBLIC_REDIRECT_SIGN= ${{ secrets.AWS_COGNITO_OAUTH_REDIRECT_SIGN }}' >> .env.production && echo 'NEXT_PUBLIC_S3_OBJECT_URL= ${{ secrets.AWS_S3_OBJECT_URL }}' >> .env.production && echo 'NEXT_PUBLIC_S3_BASE_URL= ${{ secrets.AWS_S3_BASE_URL }}' >> .env.production && echo 'NEXT_PUBLIC_HOSTING_DOMAIN= ${{ secrets.NEXT_PUBLIC_HOSTING_DOMAIN }}' >> .env.production && echo 'NEXT_PUBLIC_SLACK_CHANNEL= ${{ secrets.SLACK_CHANNEL }}' >> .env.production && echo 'NEXT_PUBLIC_SLACK_API_KEY= ${{ secrets.SLACK_API_KEY }}' >> .env.production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Blending-Client app
        run: npx serverless@2.72.2

